### PR TITLE
changes to make interaction with the Biostrings classes more easy …

### PR DESCRIPTION
**Pull request by FelixErnst**
…to interact with as proposed during review of the Modstrings package

https://github.com/Bioconductor/Contributions/issues/962

### CODE REVIEW

**Comment by hpages** [comment]
Hi Felix,

The changes look good. Only a few minor comments:

1) Using `do.call()` just for the side effect that it uses `match.fun()` internally to lookup a function by name is not a good reason enough for using `do.call()`. Please use:
```
CONSTRUCTOR_FUN <- match.fun(xsbaseclass(subject))
CONSTRUCTOR_FUN(pattern)
```
instead of:
```
do.call(xsbaseclass(subject), list(pattern))
```

Same thing for `do.call(xsbaseclass(x), list(letter))`.

2) About this:
```
seqtype <- try(seqtype(x))
if(is(seqtype,"try-error")){
    stop("'seqtype' function is not implemented for class '",class(x), "'")
}
```
The standard error message one gets when no method is defined is good enough. There is no value in trying to catch the error for the sole purpose of re-issuing your own error message, which basically says the same thing as the original message. Besides, since you're not using `silent=TRUE` when calling `try()`, the end user will see the 2 error messages: the original and yours. This is unnecessarily noisy.

So just let the call to `seqtype()` fail naturally:
```
seqtype <- seqtype(x)
```
Unfortunately there is not much that can be done to improve user-friendliness in case no `seqtype` method if defined for `x`.

3) Add alias for `xscodes` to `man/Biostrings-internals.Rd` (between the aliases for `seqtype<-` and `get_seqtype_conversion_lookup`).

4) Coding style:
  * Please use 4-space indentation
  * No curly brackets in `if () stop()` statements so:
    ```
    if (!isTRUEorFALSE(baseOnly))
        stop("'baseOnly' must be TRUE or FALSE")
    ```
    instead of:
    if (!isTRUEorFALSE(baseOnly)){
      stop("'baseOnly' must be TRUE or FALSE")
    }
    ```

Thanks!

**Comment by FelixErnst** [comment]
Hi Herve,

I made the requested changes. In addition, I wrapped the call to `match.fun`  inside a `xsbaseclass.fun` function, which can be reused (also with variable suffixes).

Thanks for the immediate response. Much appreciated!

**Comment by FelixErnst** [comment]
Hi Herve, 

since I try to make these changes in order to fascilitate the interaction with the Modstrings package, I am trying to go all in and port the dynamic constructor calls to every place it makes sense. I extended it to the `XStringSet` calls as well.

However, I have a question regarding the XString constructur, more specifically the difference in arguments of the low-level `XString` function and for example the specific high-level `BString` function. The latter is missing the `end` argument as do all the high-level constructors `AString`, `DNAString` and `RNAString`.

In the `XString,AsIs-method` the `XString` constructor is called with all arguments, which does not allow the change to the dynamic constructor using `xsbaseclass.fun`.

Do you now any reason, why the end argument is omited from the high-level constructors? Would it be ok to add them?

**Comment by FelixErnst** [comment]
So I am done with changing the constructor calls. Let me know, what you think, so that I can proceed with the Modstrings review.

How long would it take for the changes to propagate to the SPB?

**Comment by hpages** [comment]
Hi Felix,

I'm not sure I understand the need for all the new modifications you introduced since the first version of the PR. In particular I don't see the need to touch the `XStrinSet` or `XString` low-level constructors. Calling these constructors with `seqtype` set to `"ModDNA"` seems to work just fine. For example, after defining the ModDNAString class, all you need to do is define a `seqtype` method and a constructor:
```
library(Biostrings)

setClass("ModString", contains="XString")
setClass("ModDNAString", contains="ModString")

setMethod("seqtype", "ModDNAString", function(x) "ModDNA")

## This just mimics what the DNAString constructor does i.e. it's just a thin wrapper to
## the XString low-level constructor. Just for illustration purpose. Your ModDNAString
## constructor might do more complicated things:
ModDNAString <- function(x="", start=1, nchar=NA)
    Biostrings:::XString("ModDNA", x, start=start, width=nchar)
```

Then things work as expected:
```
mdna <- ModDNAString("TATACCG")
mdna
#   7-letter "ModDNAString" instance
# seq: TATACCG

matchPattern("CC", mdna)
#   Views on a 7-letter ModDNAString subject
# subject: TATACCG
# views:
#     start end width
# [1]     5   6     2 [CC]
```

For the ModDNAStringSet class, all you need to do is define the constructor as a wrapper to the XStringSet low-level constructor:
```
setClass("ModStringSet", contains="XStringSet")
setClass("ModDNAStringSet",
    contains="ModStringSet",
    prototype=prototype(elementType="ModDNAString")
)

## This just mimics what the DNAStringSet constructor does.
ModDNAStringSet <- function(x=character(), start=NA, end=NA, width=NA, use.names=TRUE)
    Biostrings:::XStringSet("ModDNA", x, start=start, end=end, width=width, use.names=use.names)
```
Then:
```
mdnaset <- ModDNAStringSet(c("AAC", "", "T"))
mdnaset
#   A ModDNAStringSet instance of length 3
#     width seq
# [1]     3 AAC
# [2]     0 
# [3]     1 T

vmatchPattern("AA", mdnaset)
# MIndex object of length 3
# [[1]]
# IRanges object with 1 range and 0 metadata columns:
#           start       end     width
#       <integer> <integer> <integer>
#   [1]         1         2         2
#
# [[2]]
# IRanges object with 0 ranges and 0 metadata columns:
#        start       end     width
#    <integer> <integer> <integer>
#
# [[3]]
# IRanges object with 0 ranges and 0 metadata columns:
#        start       end     width
#    <integer> <integer> <integer>

library(hgu95av2probe)
ModDNAStringSet(hgu95av2probe)
#   A ModDNAStringSet instance of length 201800
#          width seq
#      [1]    25 TGGCTCCTGCTGAGGTCCCCTTTCC
#      [2]    25 GGCTGTGAATTCCTGTACATATTTC
#      [3]    25 GCTTCAATTCCATTATGTTTTAATG
#      [4]    25 GCCGTTTGACAGAGCATGCTCTGCG
#      [5]    25 TGACAGAGCATGCTCTGCGTTGTTG
#      ...   ... ...
# [201796]    25 AGATGGATAGCCTTCTGTCAAAGCA
# [201797]    25 ATAGCCTTCTGTCAAAGCATCATCT
# [201798]    25 TTCTGTCAAAGCATCATCTCAACAA
# [201799]    25 CAAAGCATCATCTCAACAAGCCCTC
# [201800]    25 GTGCTCCTTGTCAACAGCGCACCCA
```
Am I missing something?

H.

**Comment by FelixErnst** [comment]
Hi Herve,

The your suggestion does immediately call internally one of the 'XString' constructors, correct? (XString.R lines 113-160). I case of the Modstrings package, I need work on the input string and replace the special characters, with the oneByteLetter before this happens, because otherwise an error gets raised in the C code. Your example will not work with the input `paste0(alphabet(ModDNAString()))`. So instead of calling `XString()`, I call `BString()` or `ModDNAString()`. The latter is implemented in the Modstrings package like this:

```
.XString <- Biostrings:::XString

.charToModString <- function(seqtype, x, start, end, width){
  x <- .convert_letters_to_one_byte_codes(x, modscodec(seqtype))
  .XString(seqtype, x, start, end, width)
}

setMethod(
  "ModString", "character",
  function(seqtype, x, start=NA, end=NA, width=NA)
  {
    if (is.null(seqtype)){
      return(.XString(seqtype, x, start, end, width))
    }
    .charToModString(seqtype, x, start, end, width)
  }
)

ModDNAString <- function(x = "", start = 1, nchar = NA){
  ModString("ModDNA", x, start = start, width = nchar)
}
```

I have to make sure that `.charToModString()` is called before `.charToXString()` in the Biostrings package is called. Otherwise it breaks with the special characters, because they are not converted using `.convert_letters_to_one_byte_codes()`.

The changes I outlined in the commits of the PR make sure this actually happens by not calling the low-level `XString("ModDNA",...)` constructor, but the high-level dispatch `ModDNAString()`. For this I introduced the `xsbaseclass.fun`/`baseclass.fun` functions to figure out which high-level constructor should be called.

Of course this approach takes one extra function call in the Biostrings package, but helps me keep many lines of code out of the Modstrings package, since I don't need to reimplement every function in which the `XString()` constructor is used. Otherwise I have to reuse the code from the Biostrings package, modify it to the specific low-level `ModString()` constructor (thereby ensuring the conversion mentioned above) and then call (in some of the functions such as `matchPattern`) the C functions of Biostrings package. This is one of the major things @mtmorgan was not happy about in the review.

With all these assumptions (I sincerely hope I haven't missed anything) the only option I have is to replace every `XString()` call with the dynamic constructor call, which directs to the specific constructor such as `ModDNAString()`.

So it is basically a trade-off. In the event that there is not a third option I missed, either the changes can go into the Biostrings package, or I have to keep more code in the Modstrings package. For me both options are totally fine and both work. The only thing I have to figure out is, how to convince @mtmorgan to accept the Modstrings package without the major changes around the C functions. 😕 

So again, In the event that there is not a third option I missed, for me it is one of the two options (or the Modstrings package gets not accepted)

**Comment by hpages** [comment]
I see. Thanks for explaining. Now that I have a better understanding of what you are trying to achieve, I came up with the [following approach](https://github.com/Bioconductor/Biostrings/commit/f2d693dee49e2cf9a8d5613ce10f204cf612beff). This is in Biostrings 2.51.3. All you should need to do with this approach is define the following methods in Modstrings:
```
setMethod("make_XString_from_string", "ModString",
    function(x0, string, start, width)
    {
        codec <- modscodec(seqtype(x0))
        string <- .convert_letters_to_one_byte_codes(string, codec)
        callNextMethod()
    }
)
setMethod("make_XStringSet_from_strings", "ModStringSet",
    function(x0, strings, start, width)
    {
        codec <- modscodec(seqtype(x0))
        strings <- vapply(strings,
            function(string)
                .convert_letters_to_one_byte_codes(string, codec),
            character(1),
            USE.NAMES=FALSE)
        callNextMethod()
    }
)
```
Then many things should work out-of-the-box so you should be able to get rid of a lot of things in Modstrings. Starting with:
- `baseclass.fun` and `xsbaseclass.fun()`
- internal utilities `.charToModString()`, `.charToModStringSet()`, `.call_new_XString_from_CHARACTER()`, and `.call_new_XStringSet_from_CHARACTER()`

But that's only the beginning. I anticipate that there are many many more things that you can remove.

For example `matchPattern()` should work out-of-the-box so there should be no need for any of the `matchPattern` methods that you define (and if it doesn't work out-of-the-box there must be a better way than copy-pasting a bunch of `matchPattern` methods and helpers from Biostrings only to modify 1 line of code in each of them).

So in the end you should be able to get rid of most of the things defined in `Modstrings-external-C-calls.R` and `Modstrings-external-functions.R`. And also get rid of the `ModString()` and `ModStringSet()` generics and methods (because `Biostrings::XString()` and `Biostrings::XStringSet()` now should do the job).
 
As for this PR, it would need to be reverted to the state it was on  Mar 6, 2019 after you made the changes I suggested in my initial review.

Thanks!

**Comment by FelixErnst** [comment]
Hi Herve,

I incorporated your changes. Thanks for having a look at it and simplifying it. However, I had to update the new generics `make_XString_from_strings` and `make_XStringSet_from_strings`, because the width of the input had to be solved after the conversion and not before. Otherwise, this lead to an error from the C function.

I updated the Modstrings package accordingly and could remove a lot of the constructor calls. (This currently is in the Biostrings-2.51.3 in the Modstrings package).

On suggestion I would make is, that the functions `XString.read` `XString.readCodes` and `XString.write` could be turned into S4 function calls as well. Currently I would be only interested in `XString.read`, since I have to use a modified version for the `letter` function and the `show` function of `ModStringViews`. What do you think?

(The `XString.write` function is currently not used in the `Biostrings` package. Maybe somewhere else)

**Comment by hpages** [comment]
I could be wrong but I suspect that the error you were getting from the C function was due to the `width(string)` or `width(strings)` vectors passed to `solveUserSEW()` being incorrect because of the presence of some multi-byte characters in `string` or `strings`. Rather than adding the `end` argument to the `make_XString_from_strings()` and `make_XStringSet_from_strings()` generics and methods, I think we should fix the `width()` method for character vectors by replacing the call to `nchar(x, type="bytes")` with `nchar(x, type="chars")`. There is some value in keeping these 2 new generics as low-level as possible. Hopefully that will make the error from the C function go away.

Now I'll take a look at your proposal about `XString.read()`.

Thanks!

**Comment by FelixErnst** [comment]
Yes, that was actually the problem, the input and the width of the input not matching. 

`nchar(x, type="chars")` would work as well, but I was very reluctant to touch it, since other stuff might depend on it and the default `type = "chars"` was overwritten for a purpose, I assume. So you do you really think this should be changed?

**Comment by hpages** [comment]
I think it's pretty safe to switch to `type="chars"`. Doing `type="bytes"` seems wrong anyway. Can't remember exactly why it was set to that. This was many years ago (12+) and it could be that `base::nchar()` was defaulting to a different `type` at that time (I think I remember seeing some improvements/changes to `base::nchar()` a few years after I introduced the `width()` method for character vectors).

I looked at your proposal about `XString.read()`. Instead of making it an S4 generic, I will introduce 2 more generics: `make_string_from_XString()` and `make_strings_from_XStringSet()` (for symmetry with `make_XString_from_string()` and `make_XStringSet_from_strings()`). I'll let you know when this is done.

**Comment by FelixErnst** [comment]
Ok. So I change the `width()` method on this branch.

**Comment by hpages** [comment]
Sorry for the delay. I reworked a few low-level things in S4Vectors and XVector.

So in the end, instead of making `XString.read()` an S4 generic, or adding the `make_string_from_XString()` and `make_strings_from_XStringSet()` generics, I decided to add the `extract_character_from_XString_by_positions()` and `extract_character_from_XString_by_ranges()` generics. See commit [here](https://github.com/Bioconductor/Biostrings/commit/12650192efa445eccaffad6f9057c4988f587d50) (this is Biostrings 2.51.4).

This approach (and naming) is more in line with what I have been doing more recently in other places (and in particular in the S4Vectors package). I want to move away from ugly things like `XString.read()`.

See long comment above the definition of these new generics in `R/XString-class.R` for how to define the methods for ModString objects.

Hope that works for you.

**Comment by FelixErnst** [comment]
I made a mistaken last time I updated the Modstrings branch in my fork directly from master instead of updating master with master. That's why the conflicts are coming up now. I cannot resolve them easily in my fork and the resulting mess will probably spill into master. I will reset my fork and update it accordingly and add a new PR. You probably can merge the new PR after that, since the changes are minimal.

**Pull request closed without merging**
