### PR TITLE
Matchprobes

### PR DESCRIPTION
**Pull request by raoulkam**

### CODE REVIEW

**Comment by hpages** [comment]
Not sure what the tittle of this PR is about. Can we use PR titles that are a little bit more descriptive? If the PR is about converting the `matchprobes.Rnw` vignette to R markdown, then the title should say so and the changes contained in the PR should stick to that. However, it looks like this PR tries to do a lot more things than that.

I think this whole migration from `.Rnw` to `.Rmd` is going to be easier to manage if we create one PR per conversion. Can we close this PR? Thanks

**Comment by raoulkam** [comment]
Thank you Herve,
Your comments are well taken, notably the descriptive nature of the title
and one PR per conversation.
Should the comment on #72 applies to all conversion?
Apart from that, the PR can be closed.

**Comment by jwokaty** [comment]
@hpages I talked to @raoulkam about doing 1 PR  for 1 conversion. At the time, there was some confusion with branching, which we also discussed. I'm going to clean this and #73, so I can review them.

**Comment by hpages** [comment]
@raoulkam 

> Should the comment on #72 applies to all conversion?

Yes.

@jwokaty Thanks for helping with this.

Closing this PR now. @raoulkam Please create a new PR with descriptive name (e.g. "Convert matchprobes.Rnw to Rmd") and with focus on that conversion only.

Thanks guys!

**Pull request closed without merging**
